display_errors=On
error_reporting=E_ALL
memory_limit=512M
date.timezone=Europe/Paris
error_log = /proc/self/fd/2
session.save_path = "/var/lib/php/sessions"
session.cookie_path = "/sso"
session.use_strict_mode = 1
session.use_only_cookies = 1
